"""Compatibility wrapper for legacy import paths.

Standalone usage should prefer `regspec_machine`.
"""

try:  # pragma: no cover - import mode differs by runtime
    from .regspec_machine import (  # noqa: F401
        CommandResult,
        ExecutionEngine,
        EngineExecution,
        NONCONFIRMATORY_MAX_TIERS,
        PresetEngine,
        REQUIRED_COLUMNS,
        RunOrchestrator,
        RUN_MODES,
        RUN_STATE_VALUES,
        RunSnapshot,
        ScanConfig,
        TIME_SERIES_AUTO_POLICY_MODES,
        TIME_SERIES_PRECHECK_MODES,
        apply_policy_split_file,
        assign_policy_document_holdout,
        build_feature_registry,
        get_git_commit,
        load_and_prepare_data,
        load_feature_registry,
        RunArtifactsContract,
        RunErrorContract,
        RunRequestContract,
        RunResultContract,
        RunStatusContract,
        run_key_factor_scan,
        select_shortlist_features_from_top_models,
        sha256_file,
        sha256_json,
    )
except ImportError:  # pragma: no cover
    from regspec_machine import (  # noqa: F401
        CommandResult,
        ExecutionEngine,
        EngineExecution,
        NONCONFIRMATORY_MAX_TIERS,
        PresetEngine,
        REQUIRED_COLUMNS,
        RunOrchestrator,
        RUN_MODES,
        RUN_STATE_VALUES,
        RunSnapshot,
        ScanConfig,
        TIME_SERIES_AUTO_POLICY_MODES,
        TIME_SERIES_PRECHECK_MODES,
        apply_policy_split_file,
        assign_policy_document_holdout,
        build_feature_registry,
        get_git_commit,
        load_and_prepare_data,
        load_feature_registry,
        RunArtifactsContract,
        RunErrorContract,
        RunRequestContract,
        RunResultContract,
        RunStatusContract,
        run_key_factor_scan,
        select_shortlist_features_from_top_models,
        sha256_file,
        sha256_json,
    )

__all__ = [
    "CommandResult",
    "ExecutionEngine",
    "EngineExecution",
    "NONCONFIRMATORY_MAX_TIERS",
    "PresetEngine",
    "REQUIRED_COLUMNS",
    "RunOrchestrator",
    "RUN_MODES",
    "RUN_STATE_VALUES",
    "RunSnapshot",
    "ScanConfig",
    "TIME_SERIES_AUTO_POLICY_MODES",
    "TIME_SERIES_PRECHECK_MODES",
    "apply_policy_split_file",
    "assign_policy_document_holdout",
    "build_feature_registry",
    "get_git_commit",
    "load_and_prepare_data",
    "load_feature_registry",
    "RunArtifactsContract",
    "RunErrorContract",
    "RunRequestContract",
    "RunResultContract",
    "RunStatusContract",
    "run_key_factor_scan",
    "select_shortlist_features_from_top_models",
    "sha256_file",
    "sha256_json",
]
